name: 'transform'
version: '1.0.0'
profile: 'transform'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  transform:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
